### PR TITLE
Add EUPL 1.2 license

### PR DESCRIPTION
**Pull request by fedjo**
Add EUPL v1.2 license

@nikoskal @arruda @rapw3k @pranavnbapat @vlf-stefan-drobic Jack Christopher et all

### CODE REVIEW

**Comment by arruda** [comment]
Seems alright, just make sure to put in the end of the README a note saying:
_This project is distributed under EUPL 1.2v. See license file for more details_ and that should be enough.
Also, I couldn't find the requirements.txt for this project, so I couldn't check it myself, but make sure that you are not using any GPL/AGPL licensed dependency. If you are using any of those, then you have to use the same license instead of the EUPL. 

if you are only using python you can use packages like:  https://pypi.org/project/liccheck/  and have it list the licenses of all your dependencies in your requirements.txt for example. 

Again, the rule of thumb is: Go with the EUPL, but if you are using any GPL/AGPL dependency, then you need to use the same license as them instead of the EUPL.

**Comment by vlf-stefan-drobic** [comment]
Right, didn't look through it last week, should probably be updated to LGPLv3.
https://www.gnu.org/licenses/why-not-lgpl.html
Shouldn't cause any issues though, it would permit the library to be used in proprietary programs.

**Comment by fedjo** [comment]
As I understand, the software that we release **CAN** be re-used/included for/in propriety applications. So in that case LGPL is valid and we should go with it.

@arruda What do you think? 

If that's the case @vlf-stefan-drobic  maybe you can create a PR adding the LICENSE to reporting service.  👯

**Comment by arruda** [comment]
Hi guys, so in the initial proposal document, we explicitly specify the EUPL license.
So we have to use it, **if we can**.

The overall steps to define our license should be as follows:
1- Start with EUPL 1.2.
2- Check if you have a more restrictive license (i.e. GPL or AGPL) on a dependency on **YOUR** project, if that's the case, replace the EUPL license with the more restrictive one.
3- If you don't have any more restrictive licensing copyleft licenses on your project dependencies, then stick with the EUPL. 


**PS**: When I say GPL/AGPL, I'm not including LGPL. (If one of your dependencies has LGPL, then that's okay; just go with step 3 and leave the EUPL license.

**Comment by fedjo** [comment]
OK then for the OCSM we can use the EUPL 1.2 language. I will merge the current PR

**Pull request merged**
